version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: zozagateway-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zoza
      POSTGRES_PASSWORD: zoza_secret
      POSTGRES_DB: zozagateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: zozagateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
